# TODO(phil): Only include what we actually need here.
filegroup(
    name = "all",
    srcs = [
        "avr-ar",
        "avr-ld",
        "avr-cpp",
        "avr-gcc",
        "avr-nm",
        "avr-objcopy",
        "avr-objdump",
        "avr-strip",
        "@avr_gcc_toolchain//:all",
    ],
    visibility = ["//tools/cpp:__subpackages__"],
)
